USE [master]

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'BITCONTAINER_AUTH_DB')
BEGIN
	CREATE DATABASE BITCONTAINER_AUTH_DB;
END
GO

USE BITCONTAINER_AUTH_DB;

IF NOT EXISTS (SELECT * FROM sysobjects where name='Users')
BEGIN
	CREATE TABLE Users (
		ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT (newid()),
		Name NVARCHAR(100) NOT NULL,
		PasswordHash NVARCHAR(200) NOT NULL,
		Salt NVARCHAR(200) NOT NULL
	);
END


