USE [master]

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'BITCONTAINER_LOGS_DB')
BEGIN
	CREATE DATABASE BITCONTAINER_LOGS_DB;
END
GO

USE BITCONTAINER_LOGS_DB;

IF NOT EXISTS (SELECT * FROM sysobjects where name='Logs')
BEGIN
	CREATE TABLE Logs (
		ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(newid()),
		Created DATETIME NOT NULL DEFAULT(getdate()),
		LogLevel VARCHAR(20) NOT NULL,
		Message NVARCHAR(500) NOT NULL,
		Exception NVARCHAR(MAX)
	);
END
